name: CI

on: [push, pull_request]

jobs:
  docs:
    name: generate vimdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate help
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./lemmy-help lua/registers.lua > doc/registers.txt

      - name: commit help
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "Auto-generate vimdoc"
          file_pattern: doc/*.txt
