name: CI

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v0.5.0, v0.6.0, v0.7.0, nightly]
    steps:
      - uses: actions/checkout@v2

      - name: install neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/${{ matrix.version }}/nvim.appimage
          chmod u+x nvim.appimage
          sudo mv nvim.appimage /usr/bin/nvim

      - name: install plenary
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: run tests
        run: make test

  docs:
    name: emmylua to vimdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate help
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./lemmy-help lua/registers.lua > doc/registers.txt

      - name: commit help
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "Auto-generate vimdoc"
          file_pattern: doc/*.txt
